name: Deploy to Prod - WEB

on:
    push:
        branches:
            - main

    workflow_dispatch:

env:
    AWS_REGION: ${{ secrets.AWS_REGION }}

permissions:
    contents: read

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]

        environment: prod

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v2
              with:
                  node-version: ${{matrix.node-version}}

            - name: Cache node modules
              uses: actions/cache@v3
              id: npm_cache_id
              with:
                  path: node_modules
                  key: ${{ runner.os }}-PROD-npm-cache-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-PROD-npm-cache-
                      ${{ runner.os }}-PROD-

            - name: Install Dependencies
              if: steps.npm_cache_id.outputs.cache-hit != 'true'
              run: npm ci

            - name: build app
              run: npm run build --if-present
              env:
                  CI: ''

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1-node16
              with:
                  aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: copy file via ssh key
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.UC_PROD_EC2_HOST_DNS }}
                  username: ${{ secrets.UC_PROD_EC2_HOST_USER_NAME }}
                  port: 22
                  key: ${{ secrets.UC_PROD_EC2_SSH_KEY }}
                  source: './build/'
                  target: '/home/ubuntu/actiondir/'

            - name: Deploye backend
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.UC_PROD_EC2_HOST_DNS }}
                  username: ${{ secrets.UC_PROD_EC2_HOST_USER_NAME  }}
                  key: ${{ secrets.UC_PROD_EC2_SSH_KEY }}
                  port: 22
                  script: |
                      sudo su
                      rm -R /var/www/html/*
                      cd /home/ubuntu/actiondir/build
                      cp * -R /var/www/html/
                      rm -R *

            # - name: Upload to S3
            #   run: aws s3 sync ./build s3://unconstrained-frontend-prod

            # - name: invalidate cache
            #   run: aws cloudfront create-invalidation --distribution-id ${{ secrets.PRD_CF_DISTRIBUTION_ID }} --paths "/*"
